// Edit this file to personalise the invitation. Image paths are relative to index.html.
// The order of sectionOrder controls the page sections; more sections can be added later.
window.INVITATION_CONFIG = {
  meta: {
    title: "Roli & Tushar — Wedding Invitation",
    description: "With the blessings of our families, we invite you to celebrate the wedding of Roli and Tushar.",
    language: "en",
  },
  theme: {
    paper: "#faf3e9",
    ink: "#49372b",
    accent: "#735139",
    gold: "#b59659",
    bodyFont: '"EB Garamond", Georgia, serif',
    nameFont: '"Great Vibes", cursive',
    // Match the R | T artwork to the original T | R champagne gold.
    monogramFilter: "brightness(0.87) saturate(1.13)",
    background: "assets/prinsep-ghat-warm-v2.png",
    backgroundPosition: "center bottom",
    backgroundOpacity: 0.98,
    backgroundBlur: "0.5px",
    whiteScreenOpacity: 0.08,
    // The open ivory centre and a gentle wash keep the family details readable.
    textWashOpacity: 0.4,
    entranceAnimation: true,
  },
  experience: {
    audio: {
      enabled: true,
      src: "assets/audio/wedding-music.mp3",
      defaultOn: true,
      loop: true,
      volume: 0.55,
      onLabel: "Turn music off",
      offLabel: "Turn music on",
      buttonSize: "48px",
      right: "18px",
      bottom: "18px",
    },
    pageWidth: "600px",
    smoothScroll: true,
    syncPageHash: true,
    coverOnRefresh: true,
    sectionTransitions: true,
    nextPageLabel: "Reveal our date",
    nextPageColour: "#7b2d3c",
    nextPagePulse: { enabled: true, durationSeconds: 3.2, scale: 1.035 },
    nextPageHideAfterVisit: true,
    petals: {
      enabled: true,
      sections: ["invitation", "saveTheDate"],
      count: 20,
      colours: ["#d6ab93", "#c6ab76", "#a6ac91"],
      deepColours: ["#a75f51", "#967443", "#687557"],
      deepOpacity: 0.68,
      opacity: 0.42,
      durationSeconds: 19,
    },
    birds: {
      enabled: true,
      sections: ["invitation", "saveTheDate"],
      count: 4,
      colour: "#826d54",
      opacity: 0.65,
      durationSeconds: 18,
    },
  },
  sectionOrder: ["cover", "invitation", "saveTheDate", "events", "moments", "withLove"],
  sections: {
    cover: {
      enabled: true,
      heading: "Our wedding invitation",
      background: "assets/radha-krishna-cover.png",
      imageAlt: "Radha and Krishna standing affectionately together beneath a floral arch",
      backgroundPosition: "center bottom",
      logo: "assets/rt-monogram-refined.png",
      logoAlt: "R | T wedding monogram",
      hashtag: "#foreverRoShar",
      hashtagFont: "Georgia, 'Times New Roman', serif",
      hashtagFontStyle: "italic",
      openLabel: "Tap to open our invitation",
      hint: "Tap to open",
      waitingHint: "A little magic is on its way…",
      tapGuidance: { enabled: true, repeatAfterIdleSeconds: 3 },
      sealLogo: "assets/rt-monogram-refined.png",
      sealPulse: {
        enabled: true,
        durationSeconds: 3.2,
        scale: 1.025,
      },
      feather: "assets/peacock-feather-client.png",
      featherLandingMilliseconds: 4800,
      featherFlight: {
        startScale: 2.7,
        landingScale: 0.78,
        landingAngle: 35,
        // Cubic curves: offsets from the seal in fractions of cover width/height.
        path: [
          [[0.33, -0.58], [0.15, -0.62], [-0.4, -0.52], [-0.23, -0.35]],
          [[-0.23, -0.35], [-0.15, -0.18], [0.38, -0.25], [0.2, -0.16]],
          [[0.2, -0.16], [0.16, -0.07], [-0.02, -0.04], [0, 0]],
        ],
      },
      envelopeFolds: true,
      openingDurationMilliseconds: 850,
      layout: {
        topPadding: "1.5svh",
        logoSize: "clamp(112px, 16svh, 152px)",
        hashtagSize: "clamp(17px, 2.3svh, 22px)",
        sealSize: "clamp(96px, 13svh, 122px)",
        sealLogoScale: 1.22,
        sealBottom: "calc(36px + 1.6svh)",
      },
    },
    invitation: {
      enabled: true,
      nextPageBottom: "56px",
      ganesh: {
        image: "assets/ganeshji.png",
        alt: "Lord Ganesha blessing the wedding",
      },
      blessing: "॥ श्री गणेशाय नमः ॥",
      blessingLanguage: "hi",
      introduction: "We request the honor of your gracious presence on the auspicious occasion of the wedding celebration of",
      // Swap these keys to change the order of the couple.
      personOrder: ["bride", "groom"],
      connector: "weds",
      people: {
        groom: {
          name: "Tushar",
          parents: "S/o Mrs. Madhu & Mr. Omm Parkash Saraogi",
          grandparents: "Grandson of Late Sarda Devi & Late Murari Lal Ji Saraogi",
        },
        bride: {
          name: "Roli",
          parents: "D/o Mrs. Nikita & Mr. Vikash Agarwal",
          grandparents: "Grand daughter of Late Bimla & Late RadheShyam Ji Agarwal",
        },
      },
    },
    saveTheDate: {
      enabled: true,
      // Uses the cover's hashtag, font and size unless overridden here.
      hashtag: {
        enabled: true,
        style: "italic",
        size: "clamp(16px, 4cqi, 19px)",
        gapAbove: "4px",
        gapBelow: "clamp(18px, 5cqi, 26px)",
      },
      nextPageLabel: "Explore the celebrations",
      background: "assets/save-the-date-background.png",
      backgroundPosition: "center center",
      // Keep the floral artwork clear. Readability comes from the card itself.
      backgroundOpacity: 1,
      backgroundBlur: "0px",
      whiteScreenOpacity: 0,
      textWashOpacity: 0,
      layout: {
        topPadding: "clamp(44px, 14cqi, 84px)",
        logoSize: "clamp(100px, 30cqi, 132px)",
        logoGap: "clamp(22px, 6cqi, 36px)",
      },
      monogram: {
        image: "assets/rt-monogram-refined.png",
        alt: "R | T gold botanical wedding monogram",
        initials: ["R", "T"],
        floating: false,
        floatDurationSeconds: 7,
      },
      scratch: {
        heading: "Scratch to reveal our special day",
        coverLabel: "SCRATCH TO REVEAL",
        coverSubtitle: "our special day",
        revealButton: "Or tap to reveal",
        revealThreshold: 0.38,
        brushSize: 28,
        coverColours: ["#f4e9d5", "#e5d0ab", "#f1e2c9"],
        coverTextColour: "#735139",
        coverSubtitleColour: "#735139",
      },
      wedding: {
        // Countdown target: start of 21 November, in Kolkata (IST).
        dateTime: "2026-11-21T00:00:00+05:30",
        timeZone: "Asia/Kolkata",
        locale: "en-IN",
        ordinalDay: true,
        label: "SAVE THE DATE",
        location: "KOLKATA",
      },
      countdown: {
        heading: "THE COUNTDOWN BEGINS",
        labels: ["Days", "Hours", "Minutes", "Seconds"],
        footer: "Until our forever begins",
        completeMessage: "Our special day is here!",
      },
      celebration: {
        enabled: true,
        count: 36,
        durationMilliseconds: 4200,
        colours: ["#c17c82", "#e2b0a0", "#cf9187", "#f0d1bd"],
      },
    },
    events: {
      enabled: true,
      background: "assets/events-background.png",
      backgroundPosition: "center center",
      backgroundOpacity: 1,
      backgroundBlur: "0px",
      whiteScreenOpacity: 0.04,
      textWashOpacity: 0,
      heading: "Celebrations",
      timeNote: "",
      nextPageLabel: "",
      dateFormat: { month: "short", commaBeforeYear: true },
      timeZone: "Asia/Kolkata",
      locale: "en-IN",
      mapLabel: "View directions",
      onwardsLabel: "onwards",
      backLinkLabel: "",
      // Change this list to reorder events; all card pictures are replaceable below.
      eventOrder: ["bhaat", "sangeet", "haldi", "baraat", "pheras"],
      venues: {
        parvati: {
          name: "Parvati Vihar Community Hall",
          address: "52/6, VIP Road, Sahabagan, Raghunathpur, Baguiati, Kolkata, West Bengal 700059",
          mapUrl: "https://maps.app.goo.gl/RGTVJhnzcfUxa39f6",
        },
        radhe: {
          name: "Radhe Palace Hotel",
          address: "882, Lake Town Road, Block A, Lake Town, South Dumdum, West Bengal 700089",
          mapUrl: "https://maps.app.goo.gl/WfWGf5iBt5UEnim66",
        },
        swastik: {
          name: "Swastik Banquets",
          address: "5th Floor, Synthesis Business Park, International Financial Hub (CBD), New Town, Kolkata, West Bengal 700156",
          mapUrl: "https://maps.app.goo.gl/ZKGjCrhxxjLtxnSM7",
        },
        wedding: {
          name: "12, Hungerford Street",
          address: "Mullick Bazar, Park Street area, Kolkata, West Bengal 700017",
          mapUrl: "https://maps.app.goo.gl/jrHQdyr3SJ93KFRVA",
        },
      },
      // Purvi's illustrations are temporary artwork until the client pictures arrive.
      items: {
        shyam: {
          title: "Ek Shaam Shyam Ke Naam",
          ceremony: "Bhajan Sandhya",
          dateTime: "2026-11-19T17:00:00+05:30",
          onwards: true,
          venue: "parvati",
          image: "assets/events/ShreeKrishna.jpeg",
          imageAlt: "Illustrated couple celebrating together",
        },
        bhaat: {
          title: "Beero Bhaat Bharan Ne Aayo",
          ceremony: "Bhaat",
          dateTime: "2026-11-20T12:30:00+05:30",
          venue: "radhe",
          image: "assets/events/myra.png",
          imageAlt: "Family presenting traditional wedding gifts at a Rajasthani Bhaat ceremony",
          imageFit: "cover",
          imagePosition: "65% center",
        },
        sangeet: {
          title: "Shaam-e-Sangeet",
          ceremony: "Sangeet",
          dateTime: "2026-11-20T18:30:00+05:30",
          onwards: true,
          venue: "swastik",
          image: "assets/events/sangeet-golden-lights.png",
          imageAlt: "Couple dancing beneath a floral arch and golden lights at their Sangeet",
          imageFit: "cover",
          imagePosition: "center center",
        },
        haldi: {
          title: "Rang Chada Haldi Ka",
          ceremony: "Haldi",
          dateTime: "2026-11-21T09:00:00+05:30",
          venue: "radhe",
          image: "assets/events/haldi-pastel-celebration.png",
          imageAlt: "Bride celebrating Haldi beneath pastel flowers with turmeric and falling petals",
          imageFit: "cover",
          imagePosition: "center 40%",
        },
        baraat: {
          title: "Band Baja Baraat",
          ceremony: "Baraat",
          dateTime: "2026-11-21T19:00:00+05:30",
          venue: "wedding",
          image: "assets/events/baraat-balcony-view.png",
          imageAlt: "Bride watching from a floral balcony as the groom arrives on horseback with the Baraat",
          imageFit: "cover",
          imagePosition: "center 60%",
        },
        pheras: {
          title: "Saat Phere, Saat Vachan",
          ceremony: "Pheras",
          dateTime: "2026-11-21T23:00:00+05:30",
          venue: "wedding",
          image: "assets/events/pheras-floral-canopy.png",
          imageAlt: "Bride and groom taking Pheras around the sacred fire beneath a floral canopy",
          imageFit: "cover",
          imagePosition: "center 60%",
        },
      },
    },
    // Add or reorder slides here. Crops use pixels from the original image.
    moments: {
      enabled: false,
      background: "assets/moments/minimal-rose-background.png",
      backgroundPosition: "center center",
      backgroundOpacity: 1,
      backgroundBlur: "0px",
      whiteScreenOpacity: 0.04,
      textWashOpacity: 0,
      heading: "Our moments of love",
      subheading: "A few of our favourite memories together",
      nextPageLabel: "",
      emptyMessage: "Photographs coming soon",
      slideshow: {
        previousLabel: "Previous photograph",
        nextLabel: "Next photograph",
        autoplay: true,
        intervalSeconds: 5,
      },
      backLinkLabel: "",
      items: [
        {
          image: "assets/moments/couple-collage.png",
          alt: "Roli and Tushar sharing a tender moment beside the lake at sunset",
          crop: { x: 1022, y: 0, width: 514, height: 582, sourceWidth: 1536, sourceHeight: 1024 },
        },
        {
          image: "assets/moments/couple-collage.png",
          alt: "Roli and Tushar smiling at each other beneath the flowers",
          crop: { x: 1110, y: 591, width: 426, height: 433, sourceWidth: 1536, sourceHeight: 1024 },
        },
        // {
        //   image: "assets/moments/couple-collage-2.png",
        //   alt: "Roli in red and Tushar in black together in a palace courtyard",
        //   crop: { x: 0, y: 0, width: 476, height: 531, sourceWidth: 1536, sourceHeight: 1024 },
        // },
        // {
        //   image: "assets/moments/couple-collage-2.png",
        //   alt: "Roli and Tushar sitting together on steps beside pink blossoms",
        //   crop: { x: 485, y: 0, width: 556, height: 531, sourceWidth: 1536, sourceHeight: 1024 },
        // },
        {
          image: "assets/moments/couple-collage-2.png",
          alt: "Tushar kissing Roli on the forehead beside the lake at sunset",
          crop: { x: 1051, y: 0, width: 485, height: 531, sourceWidth: 1536, sourceHeight: 1024 },
        },
        // {
        //   image: "assets/moments/couple-collage-2.png",
        //   alt: "Roli and Tushar walking hand in hand through the garden",
        //   crop: { x: 0, y: 539, width: 522, height: 485, sourceWidth: 1536, sourceHeight: 1024 },
        // },
        // {
        //   image: "assets/moments/couple-collage-2.png",
        //   alt: "Roli in blue resting her head on Tushar's shoulder by the lake",
        //   crop: { x: 532, y: 539, width: 529, height: 485, sourceWidth: 1536, sourceHeight: 1024 },
        // },
        {
          image: "assets/moments/couple-collage-2.png",
          alt: "Roli and Tushar in red and maroon beneath pink bougainvillea",
          crop: { x: 1070, y: 539, width: 466, height: 485, sourceWidth: 1536, sourceHeight: 1024 },
        },
      ],
    },
    withLove: {
      enabled: true,
      background: "assets/with-love-floral-background.png",
      backgroundPosition: "center center",
      backgroundOpacity: 1,
      backgroundBlur: "0px",
      whiteScreenOpacity: 0.04,
      textWashOpacity: 0,
      heading: "With Love",
      message: "Awaiting your gracious presence",
      // The family line shown beneath the message.
      family: "Vijay, Binay, Binod and the entire Agarwal family",
      // Contact people shown at the bottom.
      contactsHeading: "For any queries, please contact",
      contacts: [
        { name: "Vikash", phone: "9830563875" },
        { name: "Abhishek", phone: "8622939716" },
      ],
    },
  },
};
