// Edit this file to personalise the invitation. Image paths are relative to index.html.
// The order of sectionOrder controls the page sections; more sections can be added later.
window.INVITATION_CONFIG = {
  meta: {
    title: "Roli & Tushar — Wedding Invitation",
    description: "With the blessings of our families, we invite you to celebrate the wedding of Roli and Tushar.",
    language: "en",
  },
  theme: {
    paper: "#faf3e9",
    ink: "#49372b",
    accent: "#735139",
    gold: "#b59659",
    bodyFont: '"EB Garamond", Georgia, serif',
    nameFont: '"Great Vibes", cursive',
    background: "assets/prinsep-ghat-warm-v2.png",
    backgroundPosition: "center bottom",
    backgroundOpacity: 0.98,
    backgroundBlur: "0.5px",
    whiteScreenOpacity: 0.08,
    // The open ivory centre and a gentle wash keep the family details readable.
    textWashOpacity: 0.4,
    entranceAnimation: true,
  },
  experience: {
    pageWidth: "600px",
    smoothScroll: true,
    sectionTransitions: true,
    nextPageLabel: "Reveal our date",
    petals: {
      enabled: true,
      count: 20,
      colours: ["#d6ab93", "#c6ab76", "#a6ac91"],
      deepColours: ["#a75f51", "#967443", "#687557"],
      deepOpacity: 0.68,
      opacity: 0.42,
      durationSeconds: 19,
    },
    birds: {
      enabled: true,
      count: 4,
      colour: "#826d54",
      opacity: 0.65,
      durationSeconds: 18,
    },
  },
  sectionOrder: ["invitation", "saveTheDate", "events"],
  sections: {
    invitation: {
      enabled: true,
      nextPageBottom: "56px",
      ganesh: {
        image: "assets/ganeshji.png",
        alt: "Lord Ganesha blessing the wedding",
      },
      blessing: "॥ ॐ श्री गणेशाय नमः ॥",
      blessingLanguage: "hi",
      introduction: "We request the honor of your gracious presence on the auspicious occasion of the wedding celebration of",
      // Swap these keys to change the order of the couple.
      personOrder: ["bride", "groom"],
      connector: "weds",
      people: {
        groom: {
          name: "Tushar",
          parents: "S/o Mrs. Madhu & Mr. Omm Prakash Saraogi",
          grandparents: "Grandson of Late Mrs. Sarda Devi & Late Mr. Murari Lal Saraogi",
        },
        bride: {
          name: "Roli",
          parents: "D/o Mrs. Nikita & Mr. Vikash Agarwal",
          grandparents: "Granddaughter of Late Mrs. Bimla & Late Mr. RadheShyam Agarwal",
        },
      },
    },
    saveTheDate: {
      enabled: true,
      nextPageLabel: "Explore the celebrations",
      background: "assets/save-the-date-background.png",
      backgroundPosition: "center center",
      // Keep the floral artwork clear. Readability comes from the card itself.
      backgroundOpacity: 1,
      backgroundBlur: "0px",
      whiteScreenOpacity: 0,
      textWashOpacity: 0,
      layout: {
        topPadding: "clamp(44px, 14cqi, 84px)",
        logoSize: "clamp(100px, 30cqi, 132px)",
        logoGap: "clamp(22px, 6cqi, 36px)",
      },
      monogram: {
        image: "assets/tr-monogram-refined.png",
        alt: "T R gold botanical wedding monogram",
        initials: ["T", "R"],
        floating: true,
        floatDurationSeconds: 7,
      },
      scratch: {
        heading: "Scratch to reveal our special day",
        coverLabel: "SCRATCH TO REVEAL",
        coverSubtitle: "our special day",
        revealButton: "Or tap to reveal",
        revealThreshold: 0.38,
        brushSize: 28,
        coverColours: ["#f4e9d5", "#e5d0ab", "#f1e2c9"],
        coverTextColour: "#735139",
        coverSubtitleColour: "#735139",
      },
      wedding: {
        // Countdown target: start of 21 November, in Kolkata (IST).
        dateTime: "2026-11-21T00:00:00+05:30",
        timeZone: "Asia/Kolkata",
        locale: "en-IN",
        ordinalDay: true,
        label: "SAVE THE DATE",
        location: "KOLKATA",
      },
      countdown: {
        heading: "THE COUNTDOWN BEGINS",
        labels: ["Days", "Hours", "Minutes", "Seconds"],
        footer: "Until our forever begins",
        completeMessage: "Our special day is here!",
      },
      celebration: {
        enabled: true,
        count: 36,
        durationMilliseconds: 4200,
        colours: ["#c17c82", "#e2b0a0", "#cf9187", "#f0d1bd"],
      },
    },
    events: {
      enabled: true,
      background: "assets/events-background.png",
      backgroundPosition: "center center",
      backgroundOpacity: 1,
      backgroundBlur: "0px",
      whiteScreenOpacity: 0.04,
      textWashOpacity: 0,
      heading: "Celebrations",
      timeNote: "",
      dateFormat: { month: "short", commaBeforeYear: true },
      timeZone: "Asia/Kolkata",
      locale: "en-IN",
      mapLabel: "View directions",
      onwardsLabel: "onwards",
      backLinkLabel: "Back to our date",
      // Change this list to reorder events; all card pictures are replaceable below.
      eventOrder: ["shyam", "bhaat", "sangeet", "haldi", "baraat", "pheras"],
      venues: {
        parvati: {
          name: "Parvati Vihar",
          address: "52/6, VIP Road, Sahabagan, Raghunathpur, Baguiati, Kolkata, West Bengal 700059",
          mapUrl: "https://maps.app.goo.gl/RGTVJhnzcfUxa39f6",
        },
        radhe: {
          name: "Radhe Palace Hotel",
          address: "882, Lake Town Road, Block A, Lake Town, South Dumdum, West Bengal 700089",
          mapUrl: "https://maps.app.goo.gl/WfWGf5iBt5UEnim66",
        },
        swastik: {
          name: "Swastik Banquets",
          address: "5th Floor, Synthesis Business Park, International Financial Hub (CBD), New Town, Kolkata, West Bengal 700156",
          mapUrl: "https://maps.app.goo.gl/ZKGjCrhxxjLtxnSM7",
        },
        wedding: {
          name: "12, Hungerford Street",
          address: "Mullick Bazar, Park Street area, Kolkata, West Bengal 700017",
          mapUrl: "https://maps.app.goo.gl/jrHQdyr3SJ93KFRVA",
        },
      },
      // Purvi's illustrations are temporary artwork until the client pictures arrive.
      items: {
        shyam: {
          title: "Ek Shaam Shyam Ke Naam",
          ceremony: "Bhajan Sandhya",
          dateTime: "2026-11-19T17:00:00+05:30",
          venue: "parvati",
          image: "assets/events/purvi-6.jpg",
          imageAlt: "Illustrated couple celebrating together",
        },
        bhaat: {
          title: "Biro Bhaat Bharan Ne Aayo",
          ceremony: "Bhaat",
          dateTime: "2026-11-20T12:30:00+05:30",
          venue: "radhe",
          image: "assets/events/purvi-2.jpg",
          imageAlt: "Traditional wedding celebration illustration",
        },
        sangeet: {
          title: "Shaam-e-Sangeet",
          ceremony: "Sangeet",
          dateTime: "2026-11-20T18:00:00+05:30",
          onwards: true,
          venue: "swastik",
          image: "assets/events/purvi-3.jpg",
          imageAlt: "Illustrated couple dancing beneath a floral canopy",
        },
        haldi: {
          title: "Rang Chada Haldi Ka",
          ceremony: "Haldi",
          dateTime: "2026-11-21T09:00:00+05:30",
          venue: "radhe",
          image: "assets/events/purvi-1.jpg",
          imageAlt: "Illustrated couple against yellow marigolds",
        },
        baraat: {
          title: "Band Baja Baraat",
          ceremony: "Baraat",
          dateTime: "2026-11-21T19:00:00+05:30",
          venue: "wedding",
          image: "assets/events/purvi-4.jpg",
          imageAlt: "Illustrated groom arriving with a joyful wedding procession",
        },
        pheras: {
          title: "Saat Phere, Saat Vachan",
          ceremony: "Pheras",
          dateTime: "2026-11-21T23:00:00+05:30",
          venue: "wedding",
          image: "assets/events/purvi-5.jpg",
          imageAlt: "Illustrated couple taking wedding vows by the sacred fire",
        },
      },
    },
  },
};
